
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = SHOW_FASTFETCH=1 kitty
exec-once = nm-applet &
exec-once = mako
exec-once = waybar &
exec-once = systemctl --user start hyprpolkitagent
exec-once = blueman-applet
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/hypr/wallpaperscript/random.sh
exec-once = hypridle &
exec-once = hyprsunset &
