################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor= , highres@highrr, auto, auto
#monitor=DP-2, 1920x1080@60, auto, 1

# unscale XWayland
xwayland {
  force_zero_scaling = true
}

# toolkit-specific scale
#env = GDK_SCALE,2
env = XCURSOR_SIZE,24
